### ISSUE TITLE
PS2link fail build if use other $LANG than C

### ISSUE THREAD

**Issue by sl1pkn07** [ps2dev/ps2link#1]
hi

i have weird behavior

if make ps2link with my locale (LANG=es_ES.UTF-8), fail build with this message:

http://sl1pkn07.no-ip.com/paste/view/e741f715

but if use LANG=C, buildl OK

http://sl1pkn07.no-ip.com/paste/view/bba5307b

what happen?

greetings

**Comment by sl1pkn07** [comment]
new notice. if use the latest commit of ps2eth, now broken with all locales with the same error

EDIT: of course, I have update the ps2toolchain and ps2sdk

**Comment by Fabash** [comment]
Hi

It's an old post (1 year), but if it could help new comers (like me :-))

I had same issue, as I've freshly started with PS2SDK.
The issue seems due to the missiing '-miop' flag when using latest toolchain.
I've updated locally the ps2link/iop/Rules.make to look for iop-gcc v3.2.3 (instead of 3.2.2), as it's the latest installed with the toolchain. It has solved my issue.

ifeq ($(IOP_CC_VERSION),3.2.3)
..
endif

**Comment by sl1pkn07** [comment]
thanks! now can buils without change the locale!

very happy new year bro!
